#
###################################
# Site wide configuration
####################################
#
title: Wonjoon Goo @ UT,Austin
email: hi.wonjoon@gmail.com
description: Personal homepage of Wonjoon Goo
url: #the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          US/Central
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Wonjoon Goo
  avatar: leonids-logo.png
  job: "Ph.D. Student"
  bio: "Hello my friends"
  email: hi.wonjoon@gmail.com
  disqus-shortname:
  twitter: #username
  facebook: wonjoon.goo #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: hi.wonjoon #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
